baseURL = 'https://nepalsuyash.com.np'
languageCode = 'en-us'
theme = 'hugo-profile'
title = "Suy's Blog"


[outputs]
  home=["HTML", "RSS", "JSON"]
  page=["HTML", "RSS"]

[markup.goldmark.renderer]
  unsafe = true


[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/posts"
weight = 1

[[Menus.main]]
identifier = "gallery"
name = "Gallery"
title = "Blog posts"
url = "/gallery"
weight = 2

[params]
  title = "Suyash from n e p a l"
  description = "Passionate Software Developer interested in Web Design, Systems Programming and Generative AI"
  favicon = "/favicon.png"
  animate = true
  [params.color]
    textColor= "#343a40"
    secondaryTextColor= "#6c757d"
    textLinkColor= "#774fe3"
    backgroundColor= "#eaedf0"
    secondaryBackgroundColor= "#64ffda1a"
    primaryColor= "#774fe3"
    secondaryColor= "#f8f9fa"
  [params.color.darkmode]
    textColor= "#e4e6eb"
    secondaryTextColor= "#b0b3b8"
    textLinkColor= "#dcbc09"
    backgroundColor= "#18191a"
    secondaryBackgroundColor= "#212529"
    primaryColor= "#dcbc09"
    secondaryColor= "#212529"
  [params.hero]
    enable = true
    intro = "everyone calls me"
    title = "Suyash."
    subtitle = "I lovee computers!"
    content = "I'm a Passionate Software Developer interested in Web Design, Systems Programming and Generative AI"
    image= "/images/image.png"
[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/suynep"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-instagram"
url = "https://instagram.com/suyashnep"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fa-solid fa-book"
url = "https://aeon.co"

[params.navbar]
    align= "ms-auto" # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    disableSearch= false
    # searchPlaceholder: "Search"
    [params.navbar.stickyNavBar]
      enable = true
      showOnScrollUp = true
    enableSeparator= false
    [params.menus]
      disableAbout= false
      disableExperience= false
      disableEducation= false
      disableProjects= false
      disableAchievements= false
      disableContact= false

 [params.about]
    enable= true
    title= "Know Me Better"
    content="""
First and foremost, I'm a Software Enthusiast.
Secondly, I'm a Software Developer.
My core lies in Web Development and Systems Design.

In my free time, I love scouring through pages and pages of Philosophy, Tech, Linguistics, and everything pertaining to the same.
"""
    [params.skills]
      enable= true
      title="Here are a few technologies I've been working with recently:"
      items = ["HTML", "CSS", "JavaScript", "React", "Node", "Express"]

 [params.contact]
  enable = true
  content = "Moi inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
  btnName = "Reach Me"
  btnLink = "mailto:suy.nepal@gmail.com"

[params.footer]
[params.footer.recentPosts]
path = "posts"
count = 3
title = "Recent Writings"
enable = true
